package config

import (
	"crypto/rand"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"time"
)

type Config struct {
	ConfigPath          string
	HTTPAddr            string
	MySQLDSN            string
	CookieSecret        string
	SessionTTL          time.Duration
	RuntimeTokenTTL     time.Duration
	UDPConnectionTTL    time.Duration
	EmbeddedFRPEnabled  bool
	FRPBindAddr         string
	FRPProxyBindAddr    string
	FRPServerAddr       string
	FRPServerPort       int
	FRPTransportTLS     bool
	ClientConfigComment string
	InitialAdmin        InitialAdminConfig
	Initialized         bool
}

type InitialAdminConfig struct {
	Username     string `json:"username"`
	DisplayName  string `json:"display_name"`
	PasswordHash string `json:"password_hash"`
}

type FileConfig struct {
	MySQLDSN            string             `json:"mysql_dsn"`
	CookieSecret        string             `json:"cookie_secret"`
	SessionTTL          string             `json:"session_ttl"`
	RuntimeTokenTTL     string             `json:"runtime_token_ttl"`
	UDPConnectionTTL    string             `json:"udp_connection_ttl"`
	EmbeddedFRPEnabled  *bool              `json:"embedded_frps_enabled,omitempty"`
	FRPBindAddr         string             `json:"frp_bind_addr"`
	FRPProxyBindAddr    string             `json:"frp_proxy_bind_addr"`
	FRPServerAddr       string             `json:"frp_server_addr"`
	FRPServerPort       int                `json:"frp_server_port"`
	FRPTransportTLS     bool               `json:"frp_transport_tls"`
	ClientConfigComment string             `json:"client_config_comment"`
	InitialAdmin        InitialAdminConfig `json:"initial_admin"`
	Initialized         bool               `json:"initialized"`
	CreatedAt           time.Time          `json:"created_at"`
}

type DatabaseSetup struct {
	Host     string `json:"host"`
	Port     int    `json:"port"`
	Username string `json:"username"`
	Password string `json:"password"`
	Database string `json:"database"`
}

func Load() (Config, error) {
	cfg := defaults()
	cfg.ConfigPath = env("FRP_CONTROL_CONFIG", defaultConfigPath())

	if fileCfg, err := ReadFileConfig(cfg.ConfigPath); err == nil {
		applyFileConfig(&cfg, fileCfg)
	} else if !os.IsNotExist(err) {
		return cfg, err
	}

	applyEnv(&cfg)
	return cfg, nil
}

func defaults() Config {
	return Config{
		HTTPAddr:            env("FRP_CONTROL_HTTP_ADDR", ":8080"),
		CookieSecret:        env("FRP_CONTROL_COOKIE_SECRET", "dev-change-me-before-production"),
		SessionTTL:          envDuration("FRP_CONTROL_SESSION_TTL", time.Hour),
		RuntimeTokenTTL:     envDuration("FRP_CONTROL_RUNTIME_TOKEN_TTL", 1*time.Hour),
		UDPConnectionTTL:    envDuration("FRP_CONTROL_UDP_CONNECTION_TTL", 10*time.Second),
		EmbeddedFRPEnabled:  envBool("FRP_CONTROL_EMBEDDED_FRPS_ENABLED", true),
		FRPBindAddr:         env("FRP_CONTROL_FRP_BIND_ADDR", "0.0.0.0"),
		FRPProxyBindAddr:    env("FRP_CONTROL_FRP_PROXY_BIND_ADDR", "0.0.0.0"),
		FRPServerAddr:       env("FRP_CONTROL_FRP_SERVER_ADDR", "127.0.0.1"),
		FRPServerPort:       envInt("FRP_CONTROL_FRP_SERVER_PORT", 7000),
		FRPTransportTLS:     envBool("FRP_CONTROL_FRP_TRANSPORT_TLS", false),
		ClientConfigComment: env("FRP_CONTROL_CLIENT_CONFIG_COMMENT", "generated by frp-control-server"),
	}
}

func ReadFileConfig(path string) (FileConfig, error) {
	var cfg FileConfig
	data, err := os.ReadFile(path)
	if err != nil {
		return cfg, err
	}
	err = json.Unmarshal(data, &cfg)
	return cfg, err
}

func WriteFileConfig(path string, cfg FileConfig) error {
	if cfg.CreatedAt.IsZero() {
		cfg.CreatedAt = time.Now()
	}
	if cfg.CookieSecret == "" {
		secret, err := RandomSecret()
		if err != nil {
			return err
		}
		cfg.CookieSecret = secret
	}
	if cfg.SessionTTL == "" {
		cfg.SessionTTL = "1h"
	}
	if cfg.RuntimeTokenTTL == "" {
		cfg.RuntimeTokenTTL = "1h"
	}
	if cfg.UDPConnectionTTL == "" {
		cfg.UDPConnectionTTL = "10s"
	}
	if cfg.EmbeddedFRPEnabled == nil {
		enabled := true
		cfg.EmbeddedFRPEnabled = &enabled
	}
	if cfg.ClientConfigComment == "" {
		cfg.ClientConfigComment = "generated by frp-control-server"
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	data, err := json.MarshalIndent(cfg, "", "  ")
	if err != nil {
		return err
	}
	return os.WriteFile(path, data, 0o600)
}

func DSNFromDatabaseSetup(db DatabaseSetup) string {
	port := db.Port
	if port == 0 {
		port = 3306
	}
	return fmt.Sprintf("%s:%s@tcp(%s:%d)/%s?parseTime=true&multiStatements=true&charset=utf8mb4,utf8",
		db.Username, db.Password, db.Host, port, db.Database)
}

func RandomSecret() (string, error) {
	raw := make([]byte, 32)
	if _, err := rand.Read(raw); err != nil {
		return "", err
	}
	return base64.RawURLEncoding.EncodeToString(raw), nil
}

func (c Config) FileConfig() FileConfig {
	return FileConfig{
		MySQLDSN:            c.MySQLDSN,
		CookieSecret:        c.CookieSecret,
		SessionTTL:          c.SessionTTL.String(),
		RuntimeTokenTTL:     c.RuntimeTokenTTL.String(),
		UDPConnectionTTL:    c.UDPConnectionTTL.String(),
		EmbeddedFRPEnabled:  boolPtr(c.EmbeddedFRPEnabled),
		FRPBindAddr:         c.FRPBindAddr,
		FRPProxyBindAddr:    c.FRPProxyBindAddr,
		FRPServerAddr:       c.FRPServerAddr,
		FRPServerPort:       c.FRPServerPort,
		FRPTransportTLS:     c.FRPTransportTLS,
		ClientConfigComment: c.ClientConfigComment,
		InitialAdmin:        c.InitialAdmin,
		Initialized:         c.Initialized,
	}
}

func applyFileConfig(cfg *Config, fileCfg FileConfig) {
	cfg.MySQLDSN = fileCfg.MySQLDSN
	cfg.CookieSecret = fileCfg.CookieSecret
	cfg.SessionTTL = parseDuration(fileCfg.SessionTTL, cfg.SessionTTL)
	cfg.RuntimeTokenTTL = parseDuration(fileCfg.RuntimeTokenTTL, cfg.RuntimeTokenTTL)
	cfg.UDPConnectionTTL = parseDuration(fileCfg.UDPConnectionTTL, cfg.UDPConnectionTTL)
	if fileCfg.EmbeddedFRPEnabled != nil {
		cfg.EmbeddedFRPEnabled = *fileCfg.EmbeddedFRPEnabled
	}
	cfg.FRPBindAddr = fileCfg.FRPBindAddr
	cfg.FRPProxyBindAddr = fileCfg.FRPProxyBindAddr
	cfg.FRPServerAddr = fileCfg.FRPServerAddr
	cfg.FRPServerPort = fileCfg.FRPServerPort
	cfg.FRPTransportTLS = fileCfg.FRPTransportTLS
	cfg.ClientConfigComment = fileCfg.ClientConfigComment
	cfg.InitialAdmin = fileCfg.InitialAdmin
	cfg.Initialized = fileCfg.Initialized || fileCfg.InitialAdmin.PasswordHash != ""
	if cfg.CookieSecret == "" {
		cfg.CookieSecret = "dev-change-me-before-production"
	}
	if cfg.FRPBindAddr == "" {
		cfg.FRPBindAddr = "0.0.0.0"
	}
	if cfg.FRPProxyBindAddr == "" {
		cfg.FRPProxyBindAddr = cfg.FRPBindAddr
	}
	if cfg.FRPServerAddr == "" {
		cfg.FRPServerAddr = "127.0.0.1"
	}
	if cfg.FRPServerPort == 0 {
		cfg.FRPServerPort = 7000
	}
	if cfg.ClientConfigComment == "" {
		cfg.ClientConfigComment = "generated by frp-control-server"
	}
}

func applyEnv(cfg *Config) {
	if value := os.Getenv("FRP_CONTROL_MYSQL_DSN"); value != "" {
		cfg.MySQLDSN = value
	}
	cfg.HTTPAddr = env("FRP_CONTROL_HTTP_ADDR", cfg.HTTPAddr)
	cfg.CookieSecret = env("FRP_CONTROL_COOKIE_SECRET", cfg.CookieSecret)
	cfg.SessionTTL = envDuration("FRP_CONTROL_SESSION_TTL", cfg.SessionTTL)
	cfg.RuntimeTokenTTL = envDuration("FRP_CONTROL_RUNTIME_TOKEN_TTL", cfg.RuntimeTokenTTL)
	cfg.UDPConnectionTTL = envDuration("FRP_CONTROL_UDP_CONNECTION_TTL", cfg.UDPConnectionTTL)
	cfg.EmbeddedFRPEnabled = envBool("FRP_CONTROL_EMBEDDED_FRPS_ENABLED", cfg.EmbeddedFRPEnabled)
	cfg.FRPBindAddr = env("FRP_CONTROL_FRP_BIND_ADDR", cfg.FRPBindAddr)
	cfg.FRPProxyBindAddr = env("FRP_CONTROL_FRP_PROXY_BIND_ADDR", cfg.FRPProxyBindAddr)
	cfg.FRPServerAddr = env("FRP_CONTROL_FRP_SERVER_ADDR", cfg.FRPServerAddr)
	cfg.FRPServerPort = envInt("FRP_CONTROL_FRP_SERVER_PORT", cfg.FRPServerPort)
	cfg.FRPTransportTLS = envBool("FRP_CONTROL_FRP_TRANSPORT_TLS", cfg.FRPTransportTLS)
	cfg.ClientConfigComment = env("FRP_CONTROL_CLIENT_CONFIG_COMMENT", cfg.ClientConfigComment)
}

func defaultConfigPath() string {
	wd, err := os.Getwd()
	if err != nil {
		return "frp-control-server.cfg.json"
	}
	return filepath.Join(wd, "frp-control-server.cfg.json")
}

func env(key, fallback string) string {
	if value := os.Getenv(key); value != "" {
		return value
	}
	return fallback
}

func envInt(key string, fallback int) int {
	value := os.Getenv(key)
	if value == "" {
		return fallback
	}
	parsed, err := strconv.Atoi(value)
	if err != nil {
		return fallback
	}
	return parsed
}

func envBool(key string, fallback bool) bool {
	value := os.Getenv(key)
	if value == "" {
		return fallback
	}
	parsed, err := strconv.ParseBool(value)
	if err != nil {
		return fallback
	}
	return parsed
}

func envDuration(key string, fallback time.Duration) time.Duration {
	value := os.Getenv(key)
	if value == "" {
		return fallback
	}
	return parseDuration(value, fallback)
}

func parseDuration(value string, fallback time.Duration) time.Duration {
	parsed, err := time.ParseDuration(value)
	if err != nil {
		return fallback
	}
	return parsed
}

func ParseDuration(value string) (time.Duration, error) {
	return time.ParseDuration(value)
}

func boolPtr(value bool) *bool {
	return &value
}
